### ISSUE TITLE
ToyProject - Cut Down Mode To-Do List

### ISSUE THREAD

**Issue by seunggyun-jeong** [seunggyun-jeong/Mobile-Software-Application-with-Flutter#1]
# Cut Down Mode To-Do List
- [ ] SQLite로 데이터 저장하기
- [ ] 시간 간격 체크
- [ ] 최소 금연 시간 설정
